[package]
name = "sentiment_analyzer"
edition = "2024"

[dependencies]
anyhow = "1.0"
serde = "1.0.228"
axum = { version = "0.8.9", features = ["multipart"] }
serde_json = "1.0.149"
dotenv = "0.15.0"
chrono = "0.4.44"
uuid = { version = "1.23.1", features = ["v4", "serde"] }
tokio = { version = "1", features = ["full"] }
async-trait = "0.1"
diesel = { version = "2.3.3", features = [
    "postgres",
    "chrono",
    "serde_json",
    "uuid",
    "numeric",
] }
diesel_async = { package = "diesel-async", version = "0.7.4", features = [
    "postgres",
    "deadpool",
    "migrations",
] }
diesel_migrations = { version = "2", features = ["postgres"] }
diesel-derive-enum = { version = "2.1", features = ["postgres"] }
ort = { version = "2.0.0-rc.12", features = ["download-binaries", "ndarray"] }
tokenizers = "0.23.1"
ndarray = "0.17"
zip = "3.0"
# OpenAPI / Swagger
utoipa = { version = "5", features = ["axum_extras", "uuid", "chrono"] }
utoipa-swagger-ui = { version = "9", features = ["axum"] }

[dev-dependencies]
http-body-util = "0.1"
tower = { version = "0.5", features = ["util"] }
