services:
  postgres:
    image: postgres:latest
    container_name: postgres
    env_file:
      - ./.env
    ports:
      - '3432:3432'
    volumes:
      - postgresDb:/var/lib/postgres
volumes:
  postgresDb: